name: publish-release-build

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish-release-build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade poetry
          poetry install

      - name: Read Version and Create Tag and Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PKG_VERSION=$(poetry version --short)
          git tag v$PKG_VERSION
          git push origin v$PKG_VERSION
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/releases \
            -d '{
              "tag_name": "v'$PKG_VERSION'",
              "target_commitish": "main",
              "name": "Release v'$PKG_VERSION'",
              "body": "Description of the release",
              "draft": false,
              "prerelease": true
            }'

      - name: Upload Release Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: actions/upload-artifact
        with:
          name: release-dists
          path: dist/

      # Uncomment the following step to publish to PyPi
      # - name: Publish to PyPi
      #   env:
      #     POETRY_PYPI_TOKEN_PYPI: ${{ secrets.POETRY_PYPI_TOKEN_PYPI }}
      #   run: poetry publish
